#!/usr/bin/env bash
# biblichor bootstrap — interactive setup that gets you running in one go.
# Idempotent: re-run anytime to refresh containers without re-prompting.

set -euo pipefail

# Resolve repo root: this script lives in deploy/, so root is one up.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# ---------- colors ----------
if [[ -t 1 ]]; then
  C_BLUE=$'\e[34m'; C_GREEN=$'\e[32m'; C_YELLOW=$'\e[33m'; C_RED=$'\e[31m'; C_BOLD=$'\e[1m'; C_OFF=$'\e[0m'
else
  C_BLUE=""; C_GREEN=""; C_YELLOW=""; C_RED=""; C_BOLD=""; C_OFF=""
fi

say()  { echo "${C_BLUE}[biblichor]${C_OFF} $*"; }
ok()   { echo "${C_GREEN}[ok]${C_OFF}        $*"; }
warn() { echo "${C_YELLOW}[warn]${C_OFF}      $*"; }
die()  { echo "${C_RED}[error]${C_OFF}     $*" >&2; exit 1; }

# ---------- prereqs ----------
say "Checking prerequisites..."
command -v docker > /dev/null 2>&1 || die "docker not found. Install Docker Desktop or docker-ce first."
if ! docker compose version > /dev/null 2>&1; then
  die "docker compose plugin missing. Install docker-compose-plugin."
fi
if ! docker info > /dev/null 2>&1; then
  die "Cannot talk to the Docker daemon. Is it running?"
fi
ok "docker $(docker --version | awk '{print $3}' | tr -d ',') / compose $(docker compose version --short)"

# ---------- .env ----------
ENV_FILE="$REPO_ROOT/.env"

prompt_var() {
  # $1=var name, $2=prompt label, $3=current value (may be blank), $4=secret? (0/1)
  local name="$1" label="$2" current="${3:-}" secret="${4:-0}" value
  if [[ -n "$current" ]]; then
    if [[ "$secret" == "1" ]]; then
      printf '  %s [%s]: ' "$label" "********"
    else
      printf '  %s [%s]: ' "$label" "$current"
    fi
    read -r value
    value="${value:-$current}"
  else
    if [[ "$secret" == "1" ]]; then
      printf '  %s: ' "$label"
      read -rs value; echo
    else
      printf '  %s: ' "$label"
      read -r value
    fi
  fi
  [[ -z "$value" ]] && die "$name is required"
  printf -v "$name" '%s' "$value"
}

load_env() {
  # shellcheck source=/dev/null disable=SC1091
  if [[ -f "$ENV_FILE" ]]; then
    set -a; . "$ENV_FILE"; set +a
  fi
}

if [[ -f "$ENV_FILE" ]]; then
  say ".env already exists; pressing Enter keeps the current value."
  load_env
else
  say "No .env yet — bootstrapping a fresh one."
fi

echo
say "${C_BOLD}Required values${C_OFF}"
prompt_var GMAIL_USER          "Gmail address (used as SMTP login)"        "${GMAIL_USER:-}"          0
prompt_var GMAIL_APP_PASSWORD  "Gmail App Password (16 chars, no spaces)"   "${GMAIL_APP_PASSWORD:-}"  1
prompt_var KINDLE_EMAIL        "Send-to-Kindle address (xxx@kindle.com)"    "${KINDLE_EMAIL:-}"        0

echo
say "${C_BOLD}Optional values${C_OFF} — press Enter to accept the bracketed default."
prompt_var BIBLICHOR_PORT        "Dashboard port"                            "${BIBLICHOR_PORT:-8090}"      0
prompt_var TZ                    "Timezone (e.g. America/Los_Angeles)"       "${TZ:-Etc/UTC}"                0
echo
say "${C_BOLD}BookOrbit values${C_OFF} — library UI + reader + Kobo/KOReader/OPDS"
# Generate secrets on first run; reuse on subsequent runs.
BOOKORBIT_DB_PASSWORD="${BOOKORBIT_DB_PASSWORD:-$(openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | xxd -p | tr -d '\n')}"
BOOKORBIT_JWT_SECRET="${BOOKORBIT_JWT_SECRET:-$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p | tr -d '\n')}"
BOOKORBIT_SETUP_TOKEN="${BOOKORBIT_SETUP_TOKEN:-$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p | tr -d '\n')}"
prompt_var BOOKORBIT_PORT  "BookOrbit dashboard port"  "${BOOKORBIT_PORT:-3000}"  0
prompt_var BOOKORBIT_URL   "BookOrbit external URL (Tailscale-friendly)"  "${BOOKORBIT_URL:-http://localhost:${BOOKORBIT_PORT}}"  0

echo
say "BookOrbit admin (created on first launch)"
BOOKORBIT_ADMIN_USER="${BOOKORBIT_ADMIN_USER:-admin}"
prompt_var BOOKORBIT_ADMIN_EMAIL    "BookOrbit admin email"        "${BOOKORBIT_ADMIN_EMAIL:-}"  0
prompt_var BOOKORBIT_ADMIN_NAME     "BookOrbit admin display name" "${BOOKORBIT_ADMIN_NAME:-${BOOKORBIT_ADMIN_EMAIL%%@*}}"  0
prompt_var BOOKORBIT_ADMIN_PASSWORD "BookOrbit admin password (8+ chars, upper+lower+digit)" "${BOOKORBIT_ADMIN_PASSWORD:-}" 1

# Write .env atomically
TMP_ENV="$(mktemp)"
cat > "$TMP_ENV" <<EOF
# Generated by deploy/bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
GMAIL_USER=$GMAIL_USER
GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
KINDLE_EMAIL=$KINDLE_EMAIL
BIBLICHOR_PORT=$BIBLICHOR_PORT
TZ=$TZ
FLARESOLVERR_LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL:-info}
BIBLICHOR_USE_CLAMAV=${BIBLICHOR_USE_CLAMAV:-0}
BOOKORBIT_PORT=$BOOKORBIT_PORT
BOOKORBIT_URL=$BOOKORBIT_URL
BOOKORBIT_DB_USER=${BOOKORBIT_DB_USER:-bookorbit}
BOOKORBIT_DB_NAME=${BOOKORBIT_DB_NAME:-bookorbit}
BOOKORBIT_DB_PASSWORD=$BOOKORBIT_DB_PASSWORD
BOOKORBIT_JWT_SECRET=$BOOKORBIT_JWT_SECRET
BOOKORBIT_SETUP_TOKEN=$BOOKORBIT_SETUP_TOKEN
BOOKORBIT_NODE_HEAP_MB=${BOOKORBIT_NODE_HEAP_MB:-2048}
BOOKORBIT_ADMIN_USER=$BOOKORBIT_ADMIN_USER
BOOKORBIT_ADMIN_EMAIL=$BOOKORBIT_ADMIN_EMAIL
BOOKORBIT_ADMIN_NAME=$BOOKORBIT_ADMIN_NAME
BOOKORBIT_ADMIN_PASSWORD=$BOOKORBIT_ADMIN_PASSWORD
EOF
mv "$TMP_ENV" "$ENV_FILE"
chmod 600 "$ENV_FILE"
ok ".env written ($(wc -l < "$ENV_FILE") lines, mode 600)"

# ---------- launch ----------
COMPOSE_ARGS=( -f deploy/compose.yml --env-file "$ENV_FILE" )
if [[ "${BIBLICHOR_USE_CLAMAV:-0}" == "1" ]]; then
  COMPOSE_ARGS+=( --profile av )
  say "ClamAV enabled (--profile av)"
fi

say "Pulling images (this can take a few minutes the first time)..."
docker compose "${COMPOSE_ARGS[@]}" pull --quiet

say "Building biblichor image..."
docker compose "${COMPOSE_ARGS[@]}" build --quiet

say "Starting services..."
docker compose "${COMPOSE_ARGS[@]}" up -d

# ---------- wait until healthy ----------
HEALTH_URL="http://localhost:${BIBLICHOR_PORT}/healthz"
say "Waiting for $HEALTH_URL to return 200..."
for i in {1..40}; do
  if curl -fsS "$HEALTH_URL" > /dev/null 2>&1; then
    ok "biblichor is up after ${i}x3s"
    break
  fi
  sleep 3
  if [[ $i -eq 40 ]]; then
    warn "healthz didn't go green after 2 minutes — check 'docker compose logs biblichor'"
    exit 0
  fi
done

# ---------- wait for BookOrbit + chain admin setup ----------
BOOKORBIT_HEALTH_URL="http://localhost:${BOOKORBIT_PORT}/api/v1/health"
say "Waiting for $BOOKORBIT_HEALTH_URL (BookOrbit cold start can take ~60s)..."
for i in {1..60}; do
  if curl -fsS "$BOOKORBIT_HEALTH_URL" > /dev/null 2>&1; then
    ok "BookOrbit is up after ${i}x3s"
    break
  fi
  sleep 3
  if [[ $i -eq 60 ]]; then
    warn "BookOrbit healthz didn't go green after 3 minutes — check 'docker compose logs bookorbit'"
    warn "Skipping bookorbit-setup; run 'biblichor bookorbit-setup' manually once it's up."
    BOOKORBIT_SKIPPED=1
  fi
done

if [[ -z "${BOOKORBIT_SKIPPED:-}" ]]; then
  say "Bootstrapping BookOrbit admin + watched library..."
  # We expect biblichor to be installed in a venv (native) OR available
  # via the biblichor container's exec. Prefer native venv if present.
  if command -v biblichor > /dev/null 2>&1; then
    BIBLICHOR_BIN="biblichor"
    LIBRARY_ROOT_ARG="$REPO_ROOT/library"
  elif [[ -x "$REPO_ROOT/.venv/bin/python" ]]; then
    BIBLICHOR_BIN="$REPO_ROOT/.venv/bin/python -m endless_library"
    LIBRARY_ROOT_ARG="$REPO_ROOT/library"
  elif docker compose "${COMPOSE_ARGS[@]}" ps --status running --quiet biblichor 2>/dev/null | grep -q .; then
    # Phase 6o.5 (R-I-5): pure docker-compose deployment — exec into
    # the biblichor container so the CLI runs in the right filesystem
    # context. library_root must be the container-internal mount point
    # (Phase 6o.2 C-1 fix).
    BIBLICHOR_BIN="docker compose ${COMPOSE_ARGS[*]} exec -T biblichor python -m endless_library"
    LIBRARY_ROOT_ARG="/library"
  else
    BIBLICHOR_BIN=""
    LIBRARY_ROOT_ARG=""
  fi
  if [[ -n "$BIBLICHOR_BIN" ]]; then
    export BOOKORBIT_URL BOOKORBIT_SETUP_TOKEN BOOKORBIT_ADMIN_USER \
           BOOKORBIT_ADMIN_EMAIL BOOKORBIT_ADMIN_NAME BOOKORBIT_ADMIN_PASSWORD
    if $BIBLICHOR_BIN bookorbit-setup --library-root "$LIBRARY_ROOT_ARG" 2>&1 | sed "s|^|  |"; then
      # Phase 6o.5 (R-M-7): SETUP_BOOTSTRAP_TOKEN has no remaining
      # attack value after first-use (BookOrbit refuses /auth/setup
      # afterwards) but rotating it out of .env reduces blast radius
      # if .env ever leaks. Comment-only; the variable is left in
      # place but blanked.
      sed -i "s/^BOOKORBIT_SETUP_TOKEN=.*/BOOKORBIT_SETUP_TOKEN=  # cleared post-bootstrap/" "$ENV_FILE"
      ok "bookorbit-setup complete; SETUP_BOOTSTRAP_TOKEN cleared from .env"
    else
      warn "bookorbit-setup failed; re-run manually with: $BIBLICHOR_BIN bookorbit-setup"
    fi
  else
    warn "biblichor CLI not on PATH and no .venv detected; run manually:"
    warn "  biblichor bookorbit-setup"
  fi
fi

# ---------- report ----------
echo
echo "${C_GREEN}${C_BOLD}biblichor is running.${C_OFF}"
echo "  Dashboard:    http://localhost:${BIBLICHOR_PORT}"
echo "  Library:      http://localhost:${BOOKORBIT_PORT}  (BookOrbit — reader, Kobo/KOReader sync, OPDS)"
echo "  Healthz:      $HEALTH_URL"
echo
echo "  ${C_YELLOW}BookOrbit first-run setup:${C_OFF}"
echo "    biblichor bookorbit-setup --url http://localhost:${BOOKORBIT_PORT}"
echo
echo "Useful commands:"
echo "  docker compose ${COMPOSE_ARGS[*]} logs -f biblichor    # tail logs"
echo "  docker compose ${COMPOSE_ARGS[*]} restart biblichor    # restart"
echo "  docker compose ${COMPOSE_ARGS[*]} down                 # stop everything"
echo "  ./deploy/bootstrap.sh                                  # reconfigure"
