#!/usr/bin/env bash
# biblichor bootstrap — interactive setup that gets you running in one go.
# Idempotent: re-run anytime to refresh containers without re-prompting.

set -euo pipefail

# Resolve repo root: this script lives in deploy/, so root is one up.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# ---------- colors ----------
if [[ -t 1 ]]; then
  C_BLUE=$'\e[34m'; C_GREEN=$'\e[32m'; C_YELLOW=$'\e[33m'; C_RED=$'\e[31m'; C_BOLD=$'\e[1m'; C_OFF=$'\e[0m'
else
  C_BLUE=""; C_GREEN=""; C_YELLOW=""; C_RED=""; C_BOLD=""; C_OFF=""
fi

say()  { echo "${C_BLUE}[biblichor]${C_OFF} $*"; }
ok()   { echo "${C_GREEN}[ok]${C_OFF}        $*"; }
warn() { echo "${C_YELLOW}[warn]${C_OFF}      $*"; }
die()  { echo "${C_RED}[error]${C_OFF}     $*" >&2; exit 1; }

# ---------- prereqs ----------
say "Checking prerequisites..."
command -v docker > /dev/null 2>&1 || die "docker not found. Install Docker Desktop or docker-ce first."
if ! docker compose version > /dev/null 2>&1; then
  die "docker compose plugin missing. Install docker-compose-plugin."
fi
if ! docker info > /dev/null 2>&1; then
  die "Cannot talk to the Docker daemon. Is it running?"
fi
ok "docker $(docker --version | awk '{print $3}' | tr -d ',') / compose $(docker compose version --short)"

# ---------- .env ----------
ENV_FILE="$REPO_ROOT/.env"

prompt_var() {
  # $1=var name, $2=prompt label, $3=current value (may be blank), $4=secret? (0/1)
  local name="$1" label="$2" current="${3:-}" secret="${4:-0}" value
  if [[ -n "$current" ]]; then
    if [[ "$secret" == "1" ]]; then
      printf '  %s [%s]: ' "$label" "********"
    else
      printf '  %s [%s]: ' "$label" "$current"
    fi
    read -r value
    value="${value:-$current}"
  else
    if [[ "$secret" == "1" ]]; then
      printf '  %s: ' "$label"
      read -rs value; echo
    else
      printf '  %s: ' "$label"
      read -r value
    fi
  fi
  [[ -z "$value" ]] && die "$name is required"
  printf -v "$name" '%s' "$value"
}

load_env() {
  # shellcheck source=/dev/null disable=SC1091
  if [[ -f "$ENV_FILE" ]]; then
    set -a; . "$ENV_FILE"; set +a
  fi
}

if [[ -f "$ENV_FILE" ]]; then
  say ".env already exists; pressing Enter keeps the current value."
  load_env
else
  say "No .env yet — bootstrapping a fresh one."
fi

echo
say "${C_BOLD}Required values${C_OFF}"
prompt_var GMAIL_USER          "Gmail address (used as SMTP login)"        "${GMAIL_USER:-}"          0
prompt_var GMAIL_APP_PASSWORD  "Gmail App Password (16 chars, no spaces)"   "${GMAIL_APP_PASSWORD:-}"  1
prompt_var KINDLE_EMAIL        "Send-to-Kindle address (xxx@kindle.com)"    "${KINDLE_EMAIL:-}"        0

echo
say "${C_BOLD}Optional values${C_OFF} — press Enter to accept the bracketed default."
prompt_var BIBLICHOR_PORT        "Dashboard port"                            "${BIBLICHOR_PORT:-8090}"      0
prompt_var TZ                    "Timezone (e.g. America/Los_Angeles)"       "${TZ:-Etc/UTC}"                0
prompt_var CALIBRE_WEB_USER      "Calibre-Web admin username"                 "${CALIBRE_WEB_USER:-admin}"   0
prompt_var CALIBRE_WEB_PASSWORD  "Calibre-Web admin password (change later)"  "${CALIBRE_WEB_PASSWORD:-admin123}" 1

# Write .env atomically
TMP_ENV="$(mktemp)"
cat > "$TMP_ENV" <<EOF
# Generated by deploy/bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
GMAIL_USER=$GMAIL_USER
GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
KINDLE_EMAIL=$KINDLE_EMAIL
BIBLICHOR_PORT=$BIBLICHOR_PORT
TZ=$TZ
CALIBRE_WEB_USER=$CALIBRE_WEB_USER
CALIBRE_WEB_PASSWORD=$CALIBRE_WEB_PASSWORD
FLARESOLVERR_LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL:-info}
BIBLICHOR_USE_CLAMAV=${BIBLICHOR_USE_CLAMAV:-0}
EOF
mv "$TMP_ENV" "$ENV_FILE"
chmod 600 "$ENV_FILE"
ok ".env written ($(wc -l < "$ENV_FILE") lines, mode 600)"

# ---------- launch ----------
COMPOSE_ARGS=( -f deploy/compose.yml --env-file "$ENV_FILE" )
if [[ "${BIBLICHOR_USE_CLAMAV:-0}" == "1" ]]; then
  COMPOSE_ARGS+=( --profile av )
  say "ClamAV enabled (--profile av)"
fi

say "Pulling images (this can take a few minutes the first time)..."
docker compose "${COMPOSE_ARGS[@]}" pull --quiet

say "Building biblichor image..."
docker compose "${COMPOSE_ARGS[@]}" build --quiet

say "Starting services..."
docker compose "${COMPOSE_ARGS[@]}" up -d

# ---------- wait until healthy ----------
HEALTH_URL="http://localhost:${BIBLICHOR_PORT}/healthz"
say "Waiting for $HEALTH_URL to return 200..."
for i in {1..40}; do
  if curl -fsS "$HEALTH_URL" > /dev/null 2>&1; then
    ok "biblichor is up after ${i}x3s"
    break
  fi
  sleep 3
  if [[ $i -eq 40 ]]; then
    warn "healthz didn't go green after 2 minutes — check 'docker compose logs biblichor'"
    exit 0
  fi
done

# ---------- report ----------
echo
echo "${C_GREEN}${C_BOLD}biblichor is running.${C_OFF}"
echo "  Dashboard:   http://localhost:${BIBLICHOR_PORT}"
echo "  Library:     http://localhost:${BIBLICHOR_PORT}/library"
echo "  Healthz:     $HEALTH_URL"
echo
echo "Useful commands:"
echo "  docker compose ${COMPOSE_ARGS[*]} logs -f biblichor    # tail logs"
echo "  docker compose ${COMPOSE_ARGS[*]} restart biblichor    # restart"
echo "  docker compose ${COMPOSE_ARGS[*]} down                 # stop everything"
echo "  ./deploy/bootstrap.sh                                  # reconfigure"
